### ISSUE TITLE
Admin's Pending Job Offers List

### ISSUE THREAD

**Issue by alexanderernst** [hpi-swt2/hpi-hiwi-portal#443]
As admin I want to see a list of all pending Job Offers on top of the list of open Job Offers.
![bildschirmfoto 2014-06-09 um 15 21 17](https://cloud.githubusercontent.com/assets/1307453/3216888/17e8f326-efd9-11e3-8444-ebd9476fc25b.png)

**Comment by WGierke** [comment]
Slightly modified in #549: Don't show them always but add a possibility to filter for them.
