### ISSUE TITLE
Employer can't publish job offer for graduates

### ISSUE THREAD

**Issue by WGierke** [hpi-swt2/hpi-hiwi-portal#552]
The employer booked the premium packet but still can't publish the job offer.
It could have something to do with model/employer.rb#87

**Comment by veracl** [comment]
I cannot reproduce this error. I tried creating more than 4 graduation job offers as a partner employer which was possible, so I don't think the error is caused by model/employer.rb#87

Which employer had the problem? What did he do exactly and what was the error message?
